name: TmodsServerAddons_Wands
author: Timo Hocker
version: 1.63
main: me.tmods.serveraddons.Wands
website: http://timodsmods.weebly.com

depend: 
  - TModsServerUtils

commands:
  wand:
    description: get your magic wand!
    usage: /wand [type]
    
Permissions:
  ServerAddons.wands